// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package query

import (
	"database/sql"
	"time"
)

type User struct {
	ID        int32
	Name      sql.NullString
	Email     sql.NullString
	Address   sql.NullString
	Password  sql.NullString
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}
