// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MainResponse struct {
	IsSuccess bool              `json:"isSuccess"`
	Message   string            `json:"message"`
	Data      *UserDataResponse `json:"data,omitempty"`
	Status    int               `json:"status"`
}

type MainResponseList struct {
	IsSuccess bool                `json:"isSuccess"`
	Message   string              `json:"message"`
	Data      []*UserDataResponse `json:"data,omitempty"`
	Status    int                 `json:"status"`
}

type SignInParams struct {
	Name     string  `json:"name"`
	Email    string  `json:"email"`
	Password string  `json:"password"`
	Address  *string `json:"address,omitempty"`
}

type UserDataResponse struct {
	ID      *string `json:"Id,omitempty"`
	Name    *string `json:"name,omitempty"`
	Email   *string `json:"email,omitempty"`
	Address *string `json:"address,omitempty"`
}
