package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"

	"github.com/golang-graphql/graph"
	"github.com/golang-graphql/graph/model"
)

// User is the resolver for the User field.
func (r *queryResolver) User(ctx context.Context) (*model.AbstracModel, error) {
	// panic(fmt.Errorf("not implemented: User - User"))
	return new(model.AbstracModel), nil
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
