package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"fmt"

	"github.com/golang-graphql/graph"
	"github.com/golang-graphql/graph/model"
)

// GetUser is the resolver for the GetUser field.
func (r *userResolver) GetUser(ctx context.Context, obj *model.AbstracModel, param *model.GetUserParam) (model.UserResponseOk, error) {
	panic(fmt.Errorf("not implemented: GetUser - GetUser"))
}

// User returns graph.UserResolver implementation.
func (r *Resolver) User() graph.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
