package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"

	"github.com/golang-graphql/graph"
	"github.com/golang-graphql/graph/model"
)

// SignIn is the resolver for the SignIn field.
func (r *userResolver) SignIn(ctx context.Context, obj *model.AbstracModel, param *model.SignInParams) (*model.MainResponse, error) {
	// res := handler.

	return nil, nil
}

// GetUser is the resolver for the GetUser field.
func (r *userResolver) GetUser(ctx context.Context, obj *model.AbstracModel, param *model.GetUserParam) (*model.MainResponseList, error) {
	// panic(fmt.Errorf("not implemented: GetUser - GetUser"))
	// return handler.GetDetailUser(ctx, param)
	return nil, nil
}

// User returns graph.UserResolver implementation.
func (r *Resolver) User() graph.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
